#!/usr/bin/env bash
# Configure domain zone
func ()
{
	domain="$1"
	if [ "$2" ]
	then
		subdomain="$2"
	else
		subdomain="www lb-01 web-01 web-02"
	fi
	for su in $subdomain
	do
		echo -n "The subdomain $su"
		dig $su.$domain | grep -A1 "ANSWER SECTION:" | tail -n 1 | awk ' {print " is a " $4 " record and points to "$5}'
	done
}
func "$1" "$2"
