#!/usr/bin/env bash
# Install and configure HAproxy

sudo apt-get install -y software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.0
sudo apt-get update
sudo apt-get install -y haproxy=2.0.\*

echo "ENABLED=1" >> /etc/default/haproxy

printf %s"
frontend holberton
    bind *:80
	mode http
    default_backend webserver
backend webserver
	balance roundrobin
    server 1391-web-01 34.73.99.74:80 check
    server 1391-web-02 35.227.2.215:80 check
" >> /etc/haproxy/haproxy.cfg
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
sudo service haproxy restart
