#!/usr/bin/env bash
#manages manage_my_process
file="/var/run/my_process.pid"
case $1 in
    start)
	echo $$ > $file
	./manage_my_process &
	echo "manage_my_process started";;
    stop)
        pkill -SIGKILL -f ./manage_my_process
	sudo rm $file
	echo "manage_my_process stopped";;
    restart)
        pkill -SIGKILL -f ./manage_my_process
	sudo rm $file
	echo $$ > $file
	./manage_my_process &
	echo "manage_my_process restarted";;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
esac
