#!/bin/bash
FILENAME="/etc/passwd"
while IFS=: read -r user pass userid groupid info home shell
do
  echo "The user $user is part of the $groupid gang, lives in $home
and rides $shell. $userid's place is protected by the passcode $pass,
 more info about the user here: $info"
done < $FILENAME