#!/usr/bin/env bash
# set i to 1
i=1

# print 10 times
while [ $i -le 10 ]
do
	if [ $i = 4 ]
	then
		echo "bad luck"
	elif [ $i = 8 ]
	then
		echo "good luck"]
	else
		echo "Holberton School"
	fi
	i=$(( i+1 ))   # increments $n
done