#!/usr/bin/env bash
# set i to 1
i=1

# print 20 times
while [ $i -le 20 ]
do
	case $i in
	     4)
	     echo "bad luck from China";;
	     7)
	     echo "bad luck from Japan";;
	     17)
	     echo "bad luck from Italy";;
	     *)
	     echo $i;;
	 esac
	 i=$(( i+1 ))
done
